#!/bin/sh
#
# CircleMUD 3.0 autorun script
# Contributions by Fred Merkel, Stuart Lamble, and Jeremy Elson
# New log rotating code contributed by Peter Ajamian
# Copyright (c) 1996 The Trustees of The Johns Hopkins University
# All Rights Reserved
# See license.doc for more information
#
#############################################################################
#
# This script can be used to run CircleMUD over and over again (i.e., have it
# automatically reboot if it crashes).  It will run the game, and copy some
# of the more useful information from the system logs to the 'log' directory
# for safe keeping.
#
# You can control the operation of this script by creating and deleting files
# in Circle's root directory, either manually or by using the 'shutdown'
# command from within the MUD.
#
# Creating a file called .fastboot makes the script wait only 5 seconds
# between reboot attempts instead of the usual 60.  If you want a quick
# reboot, use the "shutdown reboot" command from within the MUD.
#
# Creating a file called .killscript makes the script terminate (i.e., stop
# rebooting the MUD).  If you want to shut down the MUD and make it stay
# shut down, use the "shutdown die" command from within the MUD.
#
# Finally, if a file called pause exists, the script will not reboot the MUD
# again until pause is removed.  This is useful if you want to turn the MUD
# off for a couple of minutes and then bring it back up without killing the
# script.  Type "shutdown pause" from within the MUD to activate this feature.
#
ulimit -c unlimited

# The port on which to run the MUD
PORT=4000

# Default flags to pass to the MUD server (see admin.txt for a description
# of all flags).
FLAGS='-q'

# Number of syslog.# files to keep in the log directory.
BACKLOGS=6

# Each record in the following variable contains information for one log file.
# The fields are filename:maxlines where filename is the name of the log file
# and maxlines is the maximum number of lines to keep in it (0 for unlimited).
# The game writes these files itself as it logs; which syslog lines go to
# which file is decided by the topic_logs table in src/utils.c.
LOGFILES='
delete:0
dts:0
rip:0
restarts:0
levels:0
rentgone:0
usage:5000
newplayers:0
errors:5000
godcmds:0
badpws:0
olc:5000
help:0
trigger:5000
'

# The following is the number of lines in syslog.CRASH.  Set to 0 to disable
# crashlogs.
LEN_CRASHLOG=30

#############################################################################

#############
# Functions #
#############

# The proc_syslog function will trim the topic files under log/ to length
# and rotate the logs in the log directory.
proc_syslog () {
  # Return if there's no syslog
  if ! [ -s syslog ]; then return; fi

  # Create the crashlog
  if [ -n "$LEN_CRASHLOG" -a "$LEN_CRASHLOG" -gt 0 ]; then
    tail -n $LEN_CRASHLOG syslog > syslog.CRASH
  fi

  # Truncate the specialty logfiles to their maximum length if applicable
  OLD_IFS=$IFS
  IFS='
'
  for rec in $LOGFILES; do
    name=log/`echo $rec|cut -f 1 -d:`
    len=`echo $rec|cut -f 2 -d:`

    # The game appends to these files itself as it logs (see
    # log_to_topic_files in src/utils.c); only the trim is ours.  A file the
    # game has not written to yet does not exist, so there is nothing to trim.
    if [ $len -gt 0 -a -f $name ]; then
      temp=`mktemp $name.XXXXXX`
      tail -n $len $name > $temp
      mv -f $temp $name
    fi
  done
  IFS=$OLD_IFS

  # Find the # to set the new log file to.
  if [ -s log/syslog.$BACKLOGS ]; then
    newlog=$(expr $BACKLOGS + 1)
  else
    newlog=1 
    while [ -s log/syslog.$newlog ]; do newlog=$(expr $newlog + 1); done 
  fi

  # Rotate the logs.
  y=2
  while [ $y -lt $newlog ]; do
    x=$(expr $y - 1)
    mv -f log/syslog.$y log/syslog.$x
    y=$(expr $y + 1)
  done
  mv -f syslog log/syslog.$newlog
}

########
# Main #
########

# Check to see if there is a syslog which would indicate that autorun
# was improperly killed (ie maybe the system was rebooted or ?).
if [ -s syslog ]; then
  echo Improper shutdown of autorun detected, rotating syslogs before startup. >> syslog
  proc_syslog
fi

# The main loop
while ( : ) do

  DATE=`date`
  echo "autorun starting game $DATE" > syslog
  echo "running bin/circle $FLAGS $PORT" >> syslog

  # On Cygwin, you may need to precede this next line with './' for
  # './bin/circle' as the command.
  nohup bin/circle $FLAGS $PORT >> syslog 2>&1

  if [ -r .killscript ]; then
    DATE=`date`;
    echo "autoscript terminated $DATE"  >> syslog
    rm .killscript
    proc_syslog
    exit
  fi

#  if [ ! -r .fastboot ]; then
#    sleep 60 
#  else
#    rm .fastboot
#  fi

  while [ -r pause ]; do
    sleep 60 
  done

  if [ -s lib/core ]; then 
    gdb bin/circle lib/core -command gdb.tmp >lib/backtrace.$(date +%d.%m.%Y.%T)
  fi

  proc_syslog
  sleep 5

done
 
 
