name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request_target:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: build
      run: cd src && touch .accepted && make
