name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: build
      working-directory: src
      run: touch .accepted && make
    - name: test
      working-directory: tests
      run: make test
    - name: publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unity Tests
        path: tests/test-results/*.xml
        reporter: java-junit
