name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download munit
      run: git submodule init && git submodule update
    - name: configure
      run: ./configure
    - name: build tests
      run: cd src && touch .accepted && make test
    - name: build
      run: make clean && make
      